// Generated by gencpp from file thin_msgs/SphericalDepthImage.msg
// DO NOT EDIT!


#ifndef THIN_MSGS_MESSAGE_SPHERICALDEPTHIMAGE_H
#define THIN_MSGS_MESSAGE_SPHERICALDEPTHIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>

namespace thin_msgs
{
template <class ContainerAllocator>
struct SphericalDepthImage_
{
  typedef SphericalDepthImage_<ContainerAllocator> Type;

  SphericalDepthImage_()
    : header()
    , horizontal_fov(0.0)
    , vertical_fov(0.0)
    , image()  {
    }
  SphericalDepthImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , horizontal_fov(0.0)
    , vertical_fov(0.0)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _horizontal_fov_type;
  _horizontal_fov_type horizontal_fov;

   typedef float _vertical_fov_type;
  _vertical_fov_type vertical_fov;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;




  typedef boost::shared_ptr< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> const> ConstPtr;

}; // struct SphericalDepthImage_

typedef ::thin_msgs::SphericalDepthImage_<std::allocator<void> > SphericalDepthImage;

typedef boost::shared_ptr< ::thin_msgs::SphericalDepthImage > SphericalDepthImagePtr;
typedef boost::shared_ptr< ::thin_msgs::SphericalDepthImage const> SphericalDepthImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thin_msgs::SphericalDepthImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'thin_msgs': ['/home/serena/catkin_ws/src/thin_drivers/thin_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28b67eb85702f0ff03ff03fbb39b252f";
  }

  static const char* value(const ::thin_msgs::SphericalDepthImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28b67eb85702f0ffULL;
  static const uint64_t static_value2 = 0x03ff03fbb39b252fULL;
};

template<class ContainerAllocator>
struct DataType< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thin_msgs/SphericalDepthImage";
  }

  static const char* value(const ::thin_msgs::SphericalDepthImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Single spherical depth image from a 3D laser range-finder\n\
#\n\
# If you have another ranging device with different behavior (e.g. a sonar\n\
# array), please find or create a different message, since applications\n\
# will make fairly laser-specific assumptions about this data\n\
\n\
Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (clockwise, if Z is down) and\n\
                         # around the positive Y axis (counterclockwise, if Y is on the left)\n\
                         # with zero angle being forward along the x axis\n\
             \n\
float32 horizontal_fov   # horizontal field of view [deg]            \n\
float32 vertical_fov     # vertical field of view [deg]   \n\
\n\
sensor_msgs/Image image  # spherical depth image [uint16]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::thin_msgs::SphericalDepthImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.horizontal_fov);
      stream.next(m.vertical_fov);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SphericalDepthImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thin_msgs::SphericalDepthImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thin_msgs::SphericalDepthImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "horizontal_fov: ";
    Printer<float>::stream(s, indent + "  ", v.horizontal_fov);
    s << indent << "vertical_fov: ";
    Printer<float>::stream(s, indent + "  ", v.vertical_fov);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THIN_MSGS_MESSAGE_SPHERICALDEPTHIMAGE_H
