// Generated by gencpp from file thin_msgs/Ticks.msg
// DO NOT EDIT!


#ifndef THIN_MSGS_MESSAGE_TICKS_H
#define THIN_MSGS_MESSAGE_TICKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace thin_msgs
{
template <class ContainerAllocator>
struct Ticks_
{
  typedef Ticks_<ContainerAllocator> Type;

  Ticks_()
    : header()
    , leftEncoder(0)
    , rightEncoder(0)  {
    }
  Ticks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , leftEncoder(0)
    , rightEncoder(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _leftEncoder_type;
  _leftEncoder_type leftEncoder;

   typedef uint16_t _rightEncoder_type;
  _rightEncoder_type rightEncoder;




  typedef boost::shared_ptr< ::thin_msgs::Ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thin_msgs::Ticks_<ContainerAllocator> const> ConstPtr;

}; // struct Ticks_

typedef ::thin_msgs::Ticks_<std::allocator<void> > Ticks;

typedef boost::shared_ptr< ::thin_msgs::Ticks > TicksPtr;
typedef boost::shared_ptr< ::thin_msgs::Ticks const> TicksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thin_msgs::Ticks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thin_msgs::Ticks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'thin_msgs': ['/home/serena/catkin_ws/src/thin_drivers/thin_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thin_msgs::Ticks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thin_msgs::Ticks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thin_msgs::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thin_msgs::Ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thin_msgs::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thin_msgs::Ticks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thin_msgs::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1154acdbb0e0a739326e90742bcd794e";
  }

  static const char* value(const ::thin_msgs::Ticks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1154acdbb0e0a739ULL;
  static const uint64_t static_value2 = 0x326e90742bcd794eULL;
};

template<class ContainerAllocator>
struct DataType< ::thin_msgs::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thin_msgs/Ticks";
  }

  static const char* value(const ::thin_msgs::Ticks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thin_msgs::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 leftEncoder\n\
uint16 rightEncoder\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::thin_msgs::Ticks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thin_msgs::Ticks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.leftEncoder);
      stream.next(m.rightEncoder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ticks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thin_msgs::Ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thin_msgs::Ticks_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftEncoder: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.leftEncoder);
    s << indent << "rightEncoder: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rightEncoder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THIN_MSGS_MESSAGE_TICKS_H
