// Generated by gencpp from file move_robot/moveGoal.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_MOVEGOAL_H
#define MOVE_ROBOT_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_robot
{
template <class ContainerAllocator>
struct moveGoal_
{
  typedef moveGoal_<ContainerAllocator> Type;

  moveGoal_()
    : goal_d(0.0)
    , goal_s(0.0)  {
    }
  moveGoal_(const ContainerAllocator& _alloc)
    : goal_d(0.0)
    , goal_s(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_d_type;
  _goal_d_type goal_d;

   typedef double _goal_s_type;
  _goal_s_type goal_s;




  typedef boost::shared_ptr< ::move_robot::moveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_robot::moveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveGoal_

typedef ::move_robot::moveGoal_<std::allocator<void> > moveGoal;

typedef boost::shared_ptr< ::move_robot::moveGoal > moveGoalPtr;
typedef boost::shared_ptr< ::move_robot::moveGoal const> moveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_robot::moveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_robot::moveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'move_robot': ['/home/serena/catkin_ws/devel/share/move_robot/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::moveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::moveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::moveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::moveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::moveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::moveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_robot::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0d0d5608172733fa01040bf6dd50f0a";
  }

  static const char* value(const ::move_robot::moveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0d0d5608172733fULL;
  static const uint64_t static_value2 = 0xa01040bf6dd50f0aULL;
};

template<class ContainerAllocator>
struct DataType< ::move_robot::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_robot/moveGoal";
  }

  static const char* value(const ::move_robot::moveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_robot::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float64 goal_d\n\
float64 goal_s\n\
";
  }

  static const char* value(const ::move_robot::moveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_robot::moveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_d);
      stream.next(m.goal_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_robot::moveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_robot::moveGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_d: ";
    Printer<double>::stream(s, indent + "  ", v.goal_d);
    s << indent << "goal_s: ";
    Printer<double>::stream(s, indent + "  ", v.goal_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_MOVEGOAL_H
