// Generated by gencpp from file navig_robot/navigGoal.msg
// DO NOT EDIT!


#ifndef NAVIG_ROBOT_MESSAGE_NAVIGGOAL_H
#define NAVIG_ROBOT_MESSAGE_NAVIGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navig_robot
{
template <class ContainerAllocator>
struct navigGoal_
{
  typedef navigGoal_<ContainerAllocator> Type;

  navigGoal_()
    : x(0.0)
    , y(0.0)
    , speed(0.0)  {
    }
  navigGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::navig_robot::navigGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navig_robot::navigGoal_<ContainerAllocator> const> ConstPtr;

}; // struct navigGoal_

typedef ::navig_robot::navigGoal_<std::allocator<void> > navigGoal;

typedef boost::shared_ptr< ::navig_robot::navigGoal > navigGoalPtr;
typedef boost::shared_ptr< ::navig_robot::navigGoal const> navigGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navig_robot::navigGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navig_robot::navigGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navig_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'navig_robot': ['/home/serena/catkin_ws/devel/share/navig_robot/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navig_robot::navigGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_robot::navigGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_robot::navigGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_robot::navigGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_robot::navigGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_robot::navigGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navig_robot::navigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7db44c9095febdd845f32851a1d81afd";
  }

  static const char* value(const ::navig_robot::navigGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7db44c9095febdd8ULL;
  static const uint64_t static_value2 = 0x45f32851a1d81afdULL;
};

template<class ContainerAllocator>
struct DataType< ::navig_robot::navigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navig_robot/navigGoal";
  }

  static const char* value(const ::navig_robot::navigGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navig_robot::navigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float64 x\n\
float64 y\n\
float64 speed\n\
";
  }

  static const char* value(const ::navig_robot::navigGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navig_robot::navigGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navigGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navig_robot::navigGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navig_robot::navigGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIG_ROBOT_MESSAGE_NAVIGGOAL_H
