// Generated by gencpp from file srrg_core_ros/BinaryNodeRelationMsg.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_BINARYNODERELATIONMSG_H
#define SRRG_CORE_ROS_MESSAGE_BINARYNODERELATIONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace srrg_core_ros
{
template <class ContainerAllocator>
struct BinaryNodeRelationMsg_
{
  typedef BinaryNodeRelationMsg_<ContainerAllocator> Type;

  BinaryNodeRelationMsg_()
    : id(0)
    , from_id(0)
    , to_id(0)
    , parent_id(0)
    , transform()
    , information_matrix()  {
      information_matrix.assign(0.0);
  }
  BinaryNodeRelationMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , from_id(0)
    , to_id(0)
    , parent_id(0)
    , transform(_alloc)
    , information_matrix()  {
  (void)_alloc;
      information_matrix.assign(0.0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _from_id_type;
  _from_id_type from_id;

   typedef int32_t _to_id_type;
  _to_id_type to_id;

   typedef int32_t _parent_id_type;
  _parent_id_type parent_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _transform_type;
  _transform_type transform;

   typedef boost::array<float, 36>  _information_matrix_type;
  _information_matrix_type information_matrix;




  typedef boost::shared_ptr< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BinaryNodeRelationMsg_

typedef ::srrg_core_ros::BinaryNodeRelationMsg_<std::allocator<void> > BinaryNodeRelationMsg;

typedef boost::shared_ptr< ::srrg_core_ros::BinaryNodeRelationMsg > BinaryNodeRelationMsgPtr;
typedef boost::shared_ptr< ::srrg_core_ros::BinaryNodeRelationMsg const> BinaryNodeRelationMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srrg_core_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'srrg_core_ros': ['/home/serena/catkin_ws/src/srrg_core_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68e53a93d9563d0a4c40ba0ca0c3435";
  }

  static const char* value(const ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68e53a93d9563d0ULL;
  static const uint64_t static_value2 = 0xa4c40ba0ca0c3435ULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg_core_ros/BinaryNodeRelationMsg";
  }

  static const char* value(const ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32 from_id\n\
int32 to_id\n\
int32 parent_id\n\
geometry_msgs/Pose transform\n\
float32[36] information_matrix\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.from_id);
      stream.next(m.to_id);
      stream.next(m.parent_id);
      stream.next(m.transform);
      stream.next(m.information_matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BinaryNodeRelationMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg_core_ros::BinaryNodeRelationMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "from_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.from_id);
    s << indent << "to_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.to_id);
    s << indent << "parent_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.parent_id);
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
    s << indent << "information_matrix[]" << std::endl;
    for (size_t i = 0; i < v.information_matrix.size(); ++i)
    {
      s << indent << "  information_matrix[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.information_matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_BINARYNODERELATIONMSG_H
