// Generated by gencpp from file srrg_core_ros/LocalMapByIdSrv.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRV_H
#define SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRV_H

#include <ros/service_traits.h>


#include <srrg_core_ros/LocalMapByIdSrvRequest.h>
#include <srrg_core_ros/LocalMapByIdSrvResponse.h>


namespace srrg_core_ros
{

struct LocalMapByIdSrv
{

typedef LocalMapByIdSrvRequest Request;
typedef LocalMapByIdSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalMapByIdSrv
} // namespace srrg_core_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srrg_core_ros::LocalMapByIdSrv > {
  static const char* value()
  {
    return "86714e02c2f6d08f328d93e752a3bf37";
  }

  static const char* value(const ::srrg_core_ros::LocalMapByIdSrv&) { return value(); }
};

template<>
struct DataType< ::srrg_core_ros::LocalMapByIdSrv > {
  static const char* value()
  {
    return "srrg_core_ros/LocalMapByIdSrv";
  }

  static const char* value(const ::srrg_core_ros::LocalMapByIdSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srrg_core_ros::LocalMapByIdSrvRequest> should match 
// service_traits::MD5Sum< ::srrg_core_ros::LocalMapByIdSrv > 
template<>
struct MD5Sum< ::srrg_core_ros::LocalMapByIdSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srrg_core_ros::LocalMapByIdSrv >::value();
  }
  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srrg_core_ros::LocalMapByIdSrvRequest> should match 
// service_traits::DataType< ::srrg_core_ros::LocalMapByIdSrv > 
template<>
struct DataType< ::srrg_core_ros::LocalMapByIdSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srrg_core_ros::LocalMapByIdSrv >::value();
  }
  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srrg_core_ros::LocalMapByIdSrvResponse> should match 
// service_traits::MD5Sum< ::srrg_core_ros::LocalMapByIdSrv > 
template<>
struct MD5Sum< ::srrg_core_ros::LocalMapByIdSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srrg_core_ros::LocalMapByIdSrv >::value();
  }
  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srrg_core_ros::LocalMapByIdSrvResponse> should match 
// service_traits::DataType< ::srrg_core_ros::LocalMapByIdSrv > 
template<>
struct DataType< ::srrg_core_ros::LocalMapByIdSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srrg_core_ros::LocalMapByIdSrv >::value();
  }
  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRV_H
