// Generated by gencpp from file srrg_core_ros/LocalMapMsg.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_LOCALMAPMSG_H
#define SRRG_CORE_ROS_MESSAGE_LOCALMAPMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <srrg_core_ros/TrajectoryNodeMsg.h>
#include <srrg_core_ros/CloudMsg.h>

namespace srrg_core_ros
{
template <class ContainerAllocator>
struct LocalMapMsg_
{
  typedef LocalMapMsg_<ContainerAllocator> Type;

  LocalMapMsg_()
    : id(0)
    , timestamp(0.0)
    , transform()
    , parents()
    , trajectory()
    , trajfull()
    , relations()
    , cloud_id(0)
    , cloud()  {
    }
  LocalMapMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , timestamp(0.0)
    , transform(_alloc)
    , parents(_alloc)
    , trajectory(_alloc)
    , trajfull(_alloc)
    , relations(_alloc)
    , cloud_id(0)
    , cloud(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _transform_type;
  _transform_type transform;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _parents_type;
  _parents_type parents;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _trajectory_type;
  _trajectory_type trajectory;

   typedef std::vector< ::srrg_core_ros::TrajectoryNodeMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::srrg_core_ros::TrajectoryNodeMsg_<ContainerAllocator> >::other >  _trajfull_type;
  _trajfull_type trajfull;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _relations_type;
  _relations_type relations;

   typedef int32_t _cloud_id_type;
  _cloud_id_type cloud_id;

   typedef  ::srrg_core_ros::CloudMsg_<ContainerAllocator>  _cloud_type;
  _cloud_type cloud;




  typedef boost::shared_ptr< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> const> ConstPtr;

}; // struct LocalMapMsg_

typedef ::srrg_core_ros::LocalMapMsg_<std::allocator<void> > LocalMapMsg;

typedef boost::shared_ptr< ::srrg_core_ros::LocalMapMsg > LocalMapMsgPtr;
typedef boost::shared_ptr< ::srrg_core_ros::LocalMapMsg const> LocalMapMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srrg_core_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'srrg_core_ros': ['/home/serena/catkin_ws/src/srrg_core_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bc12ac363b3ff95c3f4c0b85fdf820b";
  }

  static const char* value(const ::srrg_core_ros::LocalMapMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bc12ac363b3ff95ULL;
  static const uint64_t static_value2 = 0xc3f4c0b85fdf820bULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg_core_ros/LocalMapMsg";
  }

  static const char* value(const ::srrg_core_ros::LocalMapMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#cloud with trajectory, id and pose\n\
int32 id\n\
float64 timestamp\n\
geometry_msgs/Pose transform\n\
int32[] parents\n\
int32[] trajectory\n\
TrajectoryNodeMsg[] trajfull\n\
int32[] relations\n\
int32 cloud_id\n\
CloudMsg cloud\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: srrg_core_ros/TrajectoryNodeMsg\n\
#node of a trajectory\n\
uint32 seq\n\
time stamp\n\
string topic\n\
geometry_msgs/Pose transform\n\
\n\
================================================================================\n\
MSG: srrg_core_ros/CloudMsg\n\
#RawCloud msg s simple float32 collection of rich points\n\
RichPointMsg[] points\n\
================================================================================\n\
MSG: srrg_core_ros/RichPointMsg\n\
# rich point message, a point  with normal and confidence\n\
geometry_msgs/Point32 point\n\
geometry_msgs/Point32 normal\n\
geometry_msgs/Point32 rgb\n\
float32 accumulator\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::srrg_core_ros::LocalMapMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.timestamp);
      stream.next(m.transform);
      stream.next(m.parents);
      stream.next(m.trajectory);
      stream.next(m.trajfull);
      stream.next(m.relations);
      stream.next(m.cloud_id);
      stream.next(m.cloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalMapMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg_core_ros::LocalMapMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
    s << indent << "parents[]" << std::endl;
    for (size_t i = 0; i < v.parents.size(); ++i)
    {
      s << indent << "  parents[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.parents[i]);
    }
    s << indent << "trajectory[]" << std::endl;
    for (size_t i = 0; i < v.trajectory.size(); ++i)
    {
      s << indent << "  trajectory[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.trajectory[i]);
    }
    s << indent << "trajfull[]" << std::endl;
    for (size_t i = 0; i < v.trajfull.size(); ++i)
    {
      s << indent << "  trajfull[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::srrg_core_ros::TrajectoryNodeMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.trajfull[i]);
    }
    s << indent << "relations[]" << std::endl;
    for (size_t i = 0; i < v.relations.size(); ++i)
    {
      s << indent << "  relations[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.relations[i]);
    }
    s << indent << "cloud_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cloud_id);
    s << indent << "cloud: ";
    s << std::endl;
    Printer< ::srrg_core_ros::CloudMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_LOCALMAPMSG_H
