// Generated by gencpp from file srrg_core_ros/LocalMapByIdSrvResponse.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRVRESPONSE_H
#define SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <srrg_core_ros/LocalMapMsg.h>

namespace srrg_core_ros
{
template <class ContainerAllocator>
struct LocalMapByIdSrvResponse_
{
  typedef LocalMapByIdSrvResponse_<ContainerAllocator> Type;

  LocalMapByIdSrvResponse_()
    : local_map_id(0)
    , local_map()  {
    }
  LocalMapByIdSrvResponse_(const ContainerAllocator& _alloc)
    : local_map_id(0)
    , local_map(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _local_map_id_type;
  _local_map_id_type local_map_id;

   typedef  ::srrg_core_ros::LocalMapMsg_<ContainerAllocator>  _local_map_type;
  _local_map_type local_map;




  typedef boost::shared_ptr< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LocalMapByIdSrvResponse_

typedef ::srrg_core_ros::LocalMapByIdSrvResponse_<std::allocator<void> > LocalMapByIdSrvResponse;

typedef boost::shared_ptr< ::srrg_core_ros::LocalMapByIdSrvResponse > LocalMapByIdSrvResponsePtr;
typedef boost::shared_ptr< ::srrg_core_ros::LocalMapByIdSrvResponse const> LocalMapByIdSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srrg_core_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'srrg_core_ros': ['/home/serena/catkin_ws/src/srrg_core_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c85a5d39698cf98a1f7177d18b7101e";
  }

  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c85a5d39698cf98ULL;
  static const uint64_t static_value2 = 0xa1f7177d18b7101eULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg_core_ros/LocalMapByIdSrvResponse";
  }

  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 local_map_id\n\
LocalMapMsg local_map\n\
\n\
================================================================================\n\
MSG: srrg_core_ros/LocalMapMsg\n\
#cloud with trajectory, id and pose\n\
int32 id\n\
float64 timestamp\n\
geometry_msgs/Pose transform\n\
int32[] parents\n\
int32[] trajectory\n\
TrajectoryNodeMsg[] trajfull\n\
int32[] relations\n\
int32 cloud_id\n\
CloudMsg cloud\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: srrg_core_ros/TrajectoryNodeMsg\n\
#node of a trajectory\n\
uint32 seq\n\
time stamp\n\
string topic\n\
geometry_msgs/Pose transform\n\
\n\
================================================================================\n\
MSG: srrg_core_ros/CloudMsg\n\
#RawCloud msg s simple float32 collection of rich points\n\
RichPointMsg[] points\n\
================================================================================\n\
MSG: srrg_core_ros/RichPointMsg\n\
# rich point message, a point  with normal and confidence\n\
geometry_msgs/Point32 point\n\
geometry_msgs/Point32 normal\n\
geometry_msgs/Point32 rgb\n\
float32 accumulator\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_map_id);
      stream.next(m.local_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalMapByIdSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg_core_ros::LocalMapByIdSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "local_map_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.local_map_id);
    s << indent << "local_map: ";
    s << std::endl;
    Printer< ::srrg_core_ros::LocalMapMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.local_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_LOCALMAPBYIDSRVRESPONSE_H
