// Generated by gencpp from file srrg_core_ros/MapNodeUpdateMsg.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_MAPNODEUPDATEMSG_H
#define SRRG_CORE_ROS_MESSAGE_MAPNODEUPDATEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace srrg_core_ros
{
template <class ContainerAllocator>
struct MapNodeUpdateMsg_
{
  typedef MapNodeUpdateMsg_<ContainerAllocator> Type;

  MapNodeUpdateMsg_()
    : node_id(0)
    , transform()  {
    }
  MapNodeUpdateMsg_(const ContainerAllocator& _alloc)
    : node_id(0)
    , transform(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _node_id_type;
  _node_id_type node_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _transform_type;
  _transform_type transform;




  typedef boost::shared_ptr< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MapNodeUpdateMsg_

typedef ::srrg_core_ros::MapNodeUpdateMsg_<std::allocator<void> > MapNodeUpdateMsg;

typedef boost::shared_ptr< ::srrg_core_ros::MapNodeUpdateMsg > MapNodeUpdateMsgPtr;
typedef boost::shared_ptr< ::srrg_core_ros::MapNodeUpdateMsg const> MapNodeUpdateMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srrg_core_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'srrg_core_ros': ['/home/serena/catkin_ws/src/srrg_core_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb2be7510cb456fa24aa7a97c30dafbc";
  }

  static const char* value(const ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb2be7510cb456faULL;
  static const uint64_t static_value2 = 0x24aa7a97c30dafbcULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg_core_ros/MapNodeUpdateMsg";
  }

  static const char* value(const ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 node_id\n\
geometry_msgs/Pose transform\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node_id);
      stream.next(m.transform);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapNodeUpdateMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg_core_ros::MapNodeUpdateMsg_<ContainerAllocator>& v)
  {
    s << indent << "node_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node_id);
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_MAPNODEUPDATEMSG_H
