// Generated by gencpp from file srrg_core_ros/PinholeCameraInfoMsg.msg
// DO NOT EDIT!


#ifndef SRRG_CORE_ROS_MESSAGE_PINHOLECAMERAINFOMSG_H
#define SRRG_CORE_ROS_MESSAGE_PINHOLECAMERAINFOMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace srrg_core_ros
{
template <class ContainerAllocator>
struct PinholeCameraInfoMsg_
{
  typedef PinholeCameraInfoMsg_<ContainerAllocator> Type;

  PinholeCameraInfoMsg_()
    : id(0)
    , offset()
    , topic()
    , frame_id()
    , depth_scale(0.0)
    , camera_matrix()  {
      camera_matrix.assign(0.0);
  }
  PinholeCameraInfoMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , offset(_alloc)
    , topic(_alloc)
    , frame_id(_alloc)
    , depth_scale(0.0)
    , camera_matrix()  {
  (void)_alloc;
      camera_matrix.assign(0.0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _offset_type;
  _offset_type offset;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  _topic_type topic;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef float _depth_scale_type;
  _depth_scale_type depth_scale;

   typedef boost::array<float, 9>  _camera_matrix_type;
  _camera_matrix_type camera_matrix;




  typedef boost::shared_ptr< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PinholeCameraInfoMsg_

typedef ::srrg_core_ros::PinholeCameraInfoMsg_<std::allocator<void> > PinholeCameraInfoMsg;

typedef boost::shared_ptr< ::srrg_core_ros::PinholeCameraInfoMsg > PinholeCameraInfoMsgPtr;
typedef boost::shared_ptr< ::srrg_core_ros::PinholeCameraInfoMsg const> PinholeCameraInfoMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srrg_core_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'srrg_core_ros': ['/home/serena/catkin_ws/src/srrg_core_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ea9b63340a8b9a4c75f6d5e80c8df0c";
  }

  static const char* value(const ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ea9b63340a8b9a4ULL;
  static const uint64_t static_value2 = 0xc75f6d5e80c8df0cULL;
};

template<class ContainerAllocator>
struct DataType< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srrg_core_ros/PinholeCameraInfoMsg";
  }

  static const char* value(const ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
geometry_msgs/Pose offset\n\
string topic\n\
string frame_id\n\
float32 depth_scale\n\
float32[9] camera_matrix\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.offset);
      stream.next(m.topic);
      stream.next(m.frame_id);
      stream.next(m.depth_scale);
      stream.next(m.camera_matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PinholeCameraInfoMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srrg_core_ros::PinholeCameraInfoMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "offset: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.offset);
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "depth_scale: ";
    Printer<float>::stream(s, indent + "  ", v.depth_scale);
    s << indent << "camera_matrix[]" << std::endl;
    for (size_t i = 0; i < v.camera_matrix.size(); ++i)
    {
      s << indent << "  camera_matrix[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.camera_matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRRG_CORE_ROS_MESSAGE_PINHOLECAMERAINFOMSG_H
