// Generated by gencpp from file actionlib_example/LaboratorioResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIORESULT_H
#define ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_example
{
template <class ContainerAllocator>
struct LaboratorioResult_
{
  typedef LaboratorioResult_<ContainerAllocator> Type;

  LaboratorioResult_()
    : sequence()  {
    }
  LaboratorioResult_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sequence_type;
  _sequence_type sequence;




  typedef boost::shared_ptr< ::actionlib_example::LaboratorioResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_example::LaboratorioResult_<ContainerAllocator> const> ConstPtr;

}; // struct LaboratorioResult_

typedef ::actionlib_example::LaboratorioResult_<std::allocator<void> > LaboratorioResult;

typedef boost::shared_ptr< ::actionlib_example::LaboratorioResult > LaboratorioResultPtr;
typedef boost::shared_ptr< ::actionlib_example::LaboratorioResult const> LaboratorioResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_example::LaboratorioResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_example

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_example': ['/home/serena/catkin_ws/devel/share/actionlib_example/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_example::LaboratorioResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_example::LaboratorioResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_example::LaboratorioResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4e2b4f4f8682f9fa749135d7a23f2c1";
  }

  static const char* value(const ::actionlib_example::LaboratorioResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4e2b4f4f8682f9fULL;
  static const uint64_t static_value2 = 0xa749135d7a23f2c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_example/LaboratorioResult";
  }

  static const char* value(const ::actionlib_example::LaboratorioResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
float64[] sequence\n\
";
  }

  static const char* value(const ::actionlib_example::LaboratorioResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaboratorioResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_example::LaboratorioResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_example::LaboratorioResult_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIORESULT_H
