// Generated by gencpp from file actionlib_example/LaboratorioGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIOGOAL_H
#define ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_example
{
template <class ContainerAllocator>
struct LaboratorioGoal_
{
  typedef LaboratorioGoal_<ContainerAllocator> Type;

  LaboratorioGoal_()
    : order()  {
    }
  LaboratorioGoal_(const ContainerAllocator& _alloc)
    : order(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _order_type;
  _order_type order;




  typedef boost::shared_ptr< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LaboratorioGoal_

typedef ::actionlib_example::LaboratorioGoal_<std::allocator<void> > LaboratorioGoal;

typedef boost::shared_ptr< ::actionlib_example::LaboratorioGoal > LaboratorioGoalPtr;
typedef boost::shared_ptr< ::actionlib_example::LaboratorioGoal const> LaboratorioGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_example::LaboratorioGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_example

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_example': ['/home/serena/catkin_ws/devel/share/actionlib_example/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "815e5b155f124a21ff08b076ec07fb8b";
  }

  static const char* value(const ::actionlib_example::LaboratorioGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x815e5b155f124a21ULL;
  static const uint64_t static_value2 = 0xff08b076ec07fb8bULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_example/LaboratorioGoal";
  }

  static const char* value(const ::actionlib_example::LaboratorioGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition inviata dal client al server\n\
float64[] order\n\
";
  }

  static const char* value(const ::actionlib_example::LaboratorioGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaboratorioGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_example::LaboratorioGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_example::LaboratorioGoal_<ContainerAllocator>& v)
  {
    s << indent << "order[]" << std::endl;
    for (size_t i = 0; i < v.order.size(); ++i)
    {
      s << indent << "  order[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.order[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_EXAMPLE_MESSAGE_LABORATORIOGOAL_H
