(cl:defpackage srrg_core_ros-srv
  (:use )
  (:export
   "IDSSRV"
   "<IDSSRV-REQUEST>"
   "IDSSRV-REQUEST"
   "<IDSSRV-RESPONSE>"
   "IDSSRV-RESPONSE"
   "LOCALMAPBYIDSRV"
   "<LOCALMAPBYIDSRV-REQUEST>"
   "LOCALMAPBYIDSRV-REQUEST"
   "<LOCALMAPBYIDSRV-RESPONSE>"
   "LOCALMAPBYIDSRV-RESPONSE"
  ))

