(cl:defpackage actionlib_example-msg
  (:use )
  (:export
   "<LABORATORIOACTION>"
   "LABORATORIOACTION"
   "<LABORATORIOACTIONFEEDBACK>"
   "LABORATORIOACTIONFEEDBACK"
   "<LABORATORIOACTIONGOAL>"
   "LABORATORIOACTIONGOAL"
   "<LABORATORIOACTIONRESULT>"
   "LABORATORIOACTIONRESULT"
   "<LABORATORIOFEEDBACK>"
   "LABORATORIOFEEDBACK"
   "<LABORATORIOGOAL>"
   "LABORATORIOGOAL"
   "<LABORATORIORESULT>"
   "LABORATORIORESULT"
  ))

