; Auto-generated. Do not edit!


(cl:in-package actionlib_example-msg)


;//! \htmlinclude LaboratorioResult.msg.html

(cl:defclass <LaboratorioResult> (roslisp-msg-protocol:ros-message)
  ((sequence
    :reader sequence
    :initarg :sequence
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass LaboratorioResult (<LaboratorioResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LaboratorioResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LaboratorioResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_example-msg:<LaboratorioResult> is deprecated: use actionlib_example-msg:LaboratorioResult instead.")))

(cl:ensure-generic-function 'sequence-val :lambda-list '(m))
(cl:defmethod sequence-val ((m <LaboratorioResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_example-msg:sequence-val is deprecated.  Use actionlib_example-msg:sequence instead.")
  (sequence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LaboratorioResult>) ostream)
  "Serializes a message object of type '<LaboratorioResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sequence))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'sequence))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LaboratorioResult>) istream)
  "Deserializes a message object of type '<LaboratorioResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sequence) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sequence)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LaboratorioResult>)))
  "Returns string type for a message object of type '<LaboratorioResult>"
  "actionlib_example/LaboratorioResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LaboratorioResult)))
  "Returns string type for a message object of type 'LaboratorioResult"
  "actionlib_example/LaboratorioResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LaboratorioResult>)))
  "Returns md5sum for a message object of type '<LaboratorioResult>"
  "b4e2b4f4f8682f9fa749135d7a23f2c1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LaboratorioResult)))
  "Returns md5sum for a message object of type 'LaboratorioResult"
  "b4e2b4f4f8682f9fa749135d7a23f2c1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LaboratorioResult>)))
  "Returns full string definition for message of type '<LaboratorioResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64[] sequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LaboratorioResult)))
  "Returns full string definition for message of type 'LaboratorioResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64[] sequence~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LaboratorioResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sequence) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LaboratorioResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LaboratorioResult
    (cl:cons ':sequence (sequence msg))
))
