; Auto-generated. Do not edit!


(cl:in-package actionlib_example-msg)


;//! \htmlinclude LaboratorioFeedback.msg.html

(cl:defclass <LaboratorioFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LaboratorioFeedback (<LaboratorioFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LaboratorioFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LaboratorioFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_example-msg:<LaboratorioFeedback> is deprecated: use actionlib_example-msg:LaboratorioFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LaboratorioFeedback>) ostream)
  "Serializes a message object of type '<LaboratorioFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LaboratorioFeedback>) istream)
  "Deserializes a message object of type '<LaboratorioFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LaboratorioFeedback>)))
  "Returns string type for a message object of type '<LaboratorioFeedback>"
  "actionlib_example/LaboratorioFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LaboratorioFeedback)))
  "Returns string type for a message object of type 'LaboratorioFeedback"
  "actionlib_example/LaboratorioFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LaboratorioFeedback>)))
  "Returns md5sum for a message object of type '<LaboratorioFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LaboratorioFeedback)))
  "Returns md5sum for a message object of type 'LaboratorioFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LaboratorioFeedback>)))
  "Returns full string definition for message of type '<LaboratorioFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LaboratorioFeedback)))
  "Returns full string definition for message of type 'LaboratorioFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LaboratorioFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LaboratorioFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LaboratorioFeedback
))
