; Auto-generated. Do not edit!


(cl:in-package move_robot-msg)


;//! \htmlinclude moveFeedback.msg.html

(cl:defclass <moveFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass moveFeedback (<moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_robot-msg:<moveFeedback> is deprecated: use move_robot-msg:moveFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveFeedback>) ostream)
  "Serializes a message object of type '<moveFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveFeedback>) istream)
  "Deserializes a message object of type '<moveFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveFeedback>)))
  "Returns string type for a message object of type '<moveFeedback>"
  "move_robot/moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveFeedback)))
  "Returns string type for a message object of type 'moveFeedback"
  "move_robot/moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveFeedback>)))
  "Returns md5sum for a message object of type '<moveFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveFeedback)))
  "Returns md5sum for a message object of type 'moveFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveFeedback>)))
  "Returns full string definition for message of type '<moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveFeedback)))
  "Returns full string definition for message of type 'moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveFeedback
))
