; Auto-generated. Do not edit!


(cl:in-package move_robot-msg)


;//! \htmlinclude moveGoal.msg.html

(cl:defclass <moveGoal> (roslisp-msg-protocol:ros-message)
  ((goal_d
    :reader goal_d
    :initarg :goal_d
    :type cl:float
    :initform 0.0)
   (goal_s
    :reader goal_s
    :initarg :goal_s
    :type cl:float
    :initform 0.0))
)

(cl:defclass moveGoal (<moveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move_robot-msg:<moveGoal> is deprecated: use move_robot-msg:moveGoal instead.")))

(cl:ensure-generic-function 'goal_d-val :lambda-list '(m))
(cl:defmethod goal_d-val ((m <moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_robot-msg:goal_d-val is deprecated.  Use move_robot-msg:goal_d instead.")
  (goal_d m))

(cl:ensure-generic-function 'goal_s-val :lambda-list '(m))
(cl:defmethod goal_s-val ((m <moveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move_robot-msg:goal_s-val is deprecated.  Use move_robot-msg:goal_s instead.")
  (goal_s m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveGoal>) ostream)
  "Serializes a message object of type '<moveGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'goal_d))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'goal_s))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveGoal>) istream)
  "Deserializes a message object of type '<moveGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_d) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_s) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveGoal>)))
  "Returns string type for a message object of type '<moveGoal>"
  "move_robot/moveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveGoal)))
  "Returns string type for a message object of type 'moveGoal"
  "move_robot/moveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveGoal>)))
  "Returns md5sum for a message object of type '<moveGoal>"
  "c0d0d5608172733fa01040bf6dd50f0a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveGoal)))
  "Returns md5sum for a message object of type 'moveGoal"
  "c0d0d5608172733fa01040bf6dd50f0a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveGoal>)))
  "Returns full string definition for message of type '<moveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float64 goal_d~%float64 goal_s~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveGoal)))
  "Returns full string definition for message of type 'moveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float64 goal_d~%float64 goal_s~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveGoal>))
  (cl:+ 0
     8
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'moveGoal
    (cl:cons ':goal_d (goal_d msg))
    (cl:cons ':goal_s (goal_s msg))
))
