(cl:defpackage navig_robot-msg
  (:use )
  (:export
   "<NAVIGACTION>"
   "NAVIGACTION"
   "<NAVIGACTIONFEEDBACK>"
   "NAVIGACTIONFEEDBACK"
   "<NAVIGACTIONGOAL>"
   "NAVIGACTIONGOAL"
   "<NAVIGACTIONRESULT>"
   "NAVIGACTIONRESULT"
   "<NAVIGFEEDBACK>"
   "NAVIGFEEDBACK"
   "<NAVIGGOAL>"
   "NAVIGGOAL"
   "<NAVIGRESULT>"
   "NAVIGRESULT"
  ))

