; Auto-generated. Do not edit!


(cl:in-package navig_robot-msg)


;//! \htmlinclude navigFeedback.msg.html

(cl:defclass <navigFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass navigFeedback (<navigFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <navigFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'navigFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navig_robot-msg:<navigFeedback> is deprecated: use navig_robot-msg:navigFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <navigFeedback>) ostream)
  "Serializes a message object of type '<navigFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <navigFeedback>) istream)
  "Deserializes a message object of type '<navigFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<navigFeedback>)))
  "Returns string type for a message object of type '<navigFeedback>"
  "navig_robot/navigFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'navigFeedback)))
  "Returns string type for a message object of type 'navigFeedback"
  "navig_robot/navigFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<navigFeedback>)))
  "Returns md5sum for a message object of type '<navigFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'navigFeedback)))
  "Returns md5sum for a message object of type 'navigFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<navigFeedback>)))
  "Returns full string definition for message of type '<navigFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'navigFeedback)))
  "Returns full string definition for message of type 'navigFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <navigFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <navigFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'navigFeedback
))
